### ISSUE TITLE
No mention of naming conventions

### ISSUE THREAD

**Issue by meg-gutshall** [learn-co-curriculum/git-version-control-pushing-code-with-git#6]
I noticed that there isn't any mention of Git and GitHub repo naming conventions. Don't people usually name their local and remote repositories/directories the same so they don't get confused on where their local copy is stored remotely on GitHub and vice versa?

**Comment by sgharms** [comment]
Hm! Not in my experience, but I'm open to there being some break-case I'm not aware of.

I have certainly had directories that were: `back-end` but which pointed to `company-prefix-project-scala-server` and `front-end` pointed to a React app.

For me, the idea that the local name could be different than the remote "robot-name" or "fully qualified taxonomy name" than suggested by a Git URL has been more of a feature than a bug.

I also like the idea that by showing here that "whatever you name local" has no inherent bearing on what the repo must be called. An anti-mental-model might be: "In order to clone `company-prefix-project-scala-server` I must create a directory called `company-prefix-project-scala-server`"

Lastly, the second optional arguments to `git clone` in the man page are `<repository> [<directory>]` where the latter argument is the directory name of your choosing.

I'm inclined to think that not narrowing this is desirable, but if you believe otherwise, I'd gladly review a PR with the suggested change or nuance you want to bring.

**Comment by meg-gutshall** [comment]
I see what you mean—you make very valid points that I hadn't considered since I haven't gotten to the part in the curriculum where the front-end and back-end are constructed in separate repos (I'm starting JS tomorrow so I will be soon!!! 😃).

I still think it may be prudent to include a section somewhere in this lesson that briefly goes over different ways to name your repository rather than just saying "You can name it whatever you'd like; be creative!" That's pretty vague.

I researched online and though I didn't find any "best practices", I did find a trend that many developers use: `hyphenated-lowercase-naming`

  - With everything in lowercase (as opposed to camel case), you don't have to worry about mixed word interpretation between developers (i.e. `javaScriptBackEnd` vs. `javascriptBackend`)
  - Dashes are easier to type than underscores
  - The repo names are easier to read with dash separation so it allows them to be longer and more specific

However, some devs are known to follow the project and its language's conventions when naming their repos which can lead to using camel case and other naming formats.

Sources:

- [StackOverflow](https://stackoverflow.com/questions/11947587/is-there-a-naming-convention-for-git-repositories)
- [Gravity Department](https://gravitydept.com/blog/devising-a-git-repository-naming-convention)

**Comment by sgharms** [comment]
Incorporated. Thanks for the suggestion.
